export const HelpContent ={
    support: "SUPPORT",
    HC: "Help Centre",
    aboutProduct: "Everything you need to know about the product",
    question: "Frequently",
    question2: "Asked Questions",
    changeProfile: "How do i change my profile picture",
    changeProfileText: "To change your profie picture,go to settings sections, click on profie, and upload a new picture from your device.",
    changePassword: "How do i change my password",
    changePasswordText: "To change your password section,go to settings sections",
    contentType: "What type of content can i create",
    contentTypeText: "This are the type of content that you can create",
    reportContent: "How do i report content",
    reportContentText: "To report a content on our help page",
    message: "Message Admin",
    messageText: "Can't find the support you need yet? Send",
    messageText2: "a message to the admin ",
    email: "Email",
    message: "Message",

}